# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04caf37ce6582f38a64662b921cdeedbcc9cfd79520b89752ee2365be37732050e9b75edd75224f0b60de00d33cb3d52a050b286856fcc8ddbd7e27de4fb06e6

test:
  secret_key_base: ea571c4093230106f6381b8c3cff73c8c67cdd523f6d436d51645d30c48564cbb430281bcbaaf1bfcda5c429c932e52106467f1d4f6b478390df6543acb97972

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
